version: "3"

services:
  bot:
    build: ./bot
    container_name: telegram_bot
    depends_on:
      - webapp
    environment:
      - WEBAPP_URL=http://webapp:8000

  webapp:
    build: ./web-app
    container_name: fastapi_site
    ports:
      - "8000:8000"
