version: "3"

services:
  bot:
    build:
      dockerfile: botDockerfile
    container_name: telegram_bot
    depends_on:
      - webapp
    environment:
      - WEBAPP_URL=http://webapp:8000
    env_file: .env

  webapp:
    build:
      dockerfile: webappDockerfile
    container_name: fastapi_site
    ports:
      - "8000:8000"
    env_file: .env

  ngrok:
    image: ngrok/ngrok
    environment:
      NGROK_AUTHTOKEN: 2n9vnoZIelrdLQvainViTw5TrhS_7Zqf2iYPyE6MuxyymjzVY
    command: "http http://host.docker.internal:8000 --url=vertically-top-cat.ngrok-free.app"

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env

  mongo:
    image: mongo
    restart: always
    env_file: .env
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./db-data:/data/db
    networks:
      - main

networks:
  main:
    driver: bridge