version: "3"

services:
  bot:
    build: ./bot
    container_name: telegram_bot
    depends_on:
      - webapp
    environment:
      - WEBAPP_URL=http://webapp:8000
    env_file: .env

  webapp:
    build: ./webapp
    container_name: fastapi_site
    ports:
      - "8000:8000"
    env_file: .env

  ngrok:
    image: ngrok/ngrok
    environment:
      NGROK_AUTHTOKEN: 2n9vnoZIelrdLQvainViTw5TrhS_7Zqf2iYPyE6MuxyymjzVY
    command: "http http://host.docker.internal:8000 --url=vertically-top-cat.ngrok-free.app"
